config/routes.rb
Rails.application.routes.draw do
  resources :depts

  get 'static_pages/metricresults'
  get '/welcome', to:"metrics#welcome"
  get '/choose', to:"metrics#choose"
  get '/metrics/hadoop', to: "metrics#hadoop"
  get '/metrics/bash', to: "metrics#bash"

  resources :metrics

   root 'metrics#welcome'

end

app/models/dept.rb
class Dept < ActiveRecord::Base
  DEPT_OPTIONS = {'ECE' => 1, 'CS' => 2, 'EE' => 3,'Custom' => 4}
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render :show, status: :created, location: @dept }
      else
        format.html { render :new }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @dept }
      else
        format.html { render :edit }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url, notice: 'Dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params.require(:dept).permit(:deptname, :dept_id)
    end
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deptname %><br>
    <%= f.text_field :deptname %>
  </div>
  <div class="field">
    <%= f.label :dept_id %><br>
    <%= f.number_field :dept_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depts/edit.html.erb
<h1>Editing dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

app/views/depts/index.html.erb
<h1>Listing depts</h1>

<table>
  <thead>
    <tr>
      <th>Deptname</th>
      <th>Dept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
        <td><%= dept.deptname %></td>
        <td><%= dept.dept_id %></td>
        <td><%= link_to 'Show', dept %></td>
        <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
        <td><%= link_to 'Destroy', dept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dept', new_dept_path %>

app/views/depts/new.html.erb
<h1>New dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deptname:</strong>
  <%= @dept.deptname %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @dept.dept_id %>
</p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>